[2023-06-06T00:21:54.926+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: process_weather_people_postgres.group_users.slack_notification_1 scheduled__2023-06-04T00:00:00+00:00 [queued]>
[2023-06-06T00:21:54.937+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: process_weather_people_postgres.group_users.slack_notification_1 scheduled__2023-06-04T00:00:00+00:00 [queued]>
[2023-06-06T00:21:54.938+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-06T00:21:54.938+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 5
[2023-06-06T00:21:54.938+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-06T00:21:54.953+0000] {taskinstance.py:1383} INFO - Executing <Task(ClimateNotificationSlackOperator): group_users.slack_notification_1> on 2023-06-04 00:00:00+00:00
[2023-06-06T00:21:54.961+0000] {standard_task_runner.py:55} INFO - Started process 14420 to run task
[2023-06-06T00:21:54.964+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'process_weather_people_postgres', 'group_users.slack_notification_1', 'scheduled__2023-06-04T00:00:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/process_weather_people_postgres/process_weather_people_postgres.py', '--cfg-path', '/tmp/tmpeaiuueel']
[2023-06-06T00:21:54.966+0000] {standard_task_runner.py:83} INFO - Job 130: Subtask group_users.slack_notification_1
[2023-06-06T00:21:55.022+0000] {task_command.py:376} INFO - Running <TaskInstance: process_weather_people_postgres.group_users.slack_notification_1 scheduled__2023-06-04T00:00:00+00:00 [running]> on host 1160da0dacdb
[2023-06-06T00:21:55.083+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=data_eng
AIRFLOW_CTX_DAG_ID=process_weather_people_postgres
AIRFLOW_CTX_TASK_ID=group_users.slack_notification_1
AIRFLOW_CTX_EXECUTION_DATE=2023-06-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-04T00:00:00+00:00
[2023-06-06T00:21:55.084+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/others/operators/climate_temperature_slack.py", line 48, in execute
    if not isinstance(self.table_predicate, str):
AttributeError: 'ClimateNotificationSlackOperator' object has no attribute 'table_predicate'
[2023-06-06T00:21:55.091+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=process_weather_people_postgres, task_id=group_users.slack_notification_1, execution_date=20230604T000000, start_date=20230606T002154, end_date=20230606T002155
[2023-06-06T00:21:55.103+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 130 for task group_users.slack_notification_1 ('ClimateNotificationSlackOperator' object has no attribute 'table_predicate'; 14420)
[2023-06-06T00:21:55.136+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-06T00:21:55.163+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
